version: '3.7'

services: 

  claim_gateway:
    container_name: claim-gateway
    build: claim-gateway/.
    ports:
      - "8080:8080"
    environment:
      micronaut.http.services.claim-user.url: http://claim-user-ms:8081  
    networks:  
      - claim-microservices  

  cliam_user_ms:
    container_name: claim-user-ms
    build: claim-user/.
    networks:  
      - claim-microservices

networks:
  claim-microservices:
    driver: bridge